# Generated by Django 2.0.4 on 2018-04-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
